FROM docker:24-dind

WORKDIR /app

# Installe docker-compose VIA APK (plus propre, pas d'erreur PEP 668)
RUN apk add --no-cache docker-compose

# Copie tout le code
COPY . .

# Expose les ports
EXPOSE 3000 8000

# Lance docker-compose
CMD ["docker-compose", "up", "--build"]
